server:
  port: 9820

logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

spring:
  data:
    mongodb:
      host: localhost
      database: octopus

storage:
  minio:
    endpoint: http://localhost:9000
    accesskey: minio
    secretkey: miniostorage
    buckets:
      image: octopus-image