server:
  port: 9820

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

spring:
  data:
    mongodb:
      host: localhost

storage:
  minio:
    endpoint: http://localhost:9000
    accesskey：minio
    secretkey: miniostorage